"""Generate Dropbear-native synthetic motion clips (semantic space -> motors) as contract motion CSVs.

Clips: stand, wave_right, arm_swing, weight_shift, squat_lite (see dropbear_wbc.motion.synthetic).
Output: ``<out-root>/synthetic/<clip>.csv`` + ``.json`` + ``semantic/<clip>.semantic.csv`` at 50 Hz.

Examples::

    python tools/make_synthetic_motion.py                       # all clips, real calibration
    python tools/make_synthetic_motion.py --clips stand,squat_lite \
        --calibration tests/fixtures/mock_semantic_calibration.json --allow-mock   # -> data/motions_mock
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
for p in (REPO / "source", REPO / "third_party" / "pydeps"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from dropbear_wbc.motion.calibration_view import DEFAULT_CALIBRATION, load_calibration  # noqa: E402
from dropbear_wbc.motion.g1_to_dropbear import semantic_to_dropbear  # noqa: E402
from dropbear_wbc.motion.motion_csv import validate_motion_files, write_motion  # noqa: E402
from dropbear_wbc.motion.pipeline import PIPELINE_VERSION  # noqa: E402
from dropbear_wbc.motion.synthetic import FPS, SYNTHETIC_CLIPS, make_clip  # noqa: E402

DEFAULT_OUT = REPO / "data" / "motions"
MOCK_OUT = REPO / "data" / "motions_mock"
LICENSE = {
    "license": "dropbear-wbc-generated",
    "summary": "Procedurally generated by tools/make_synthetic_motion.py; contains no third-party motion data.",
    "redistributable": True,
    "url": "",
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--clips", default="all", help=f"comma list of {list(SYNTHETIC_CLIPS)} or 'all'")
    ap.add_argument("--calibration", type=Path, default=DEFAULT_CALIBRATION)
    ap.add_argument("--allow-mock", action="store_true")
    ap.add_argument("--out-root", type=Path, default=None)
    args = ap.parse_args(argv)

    cal = load_calibration(args.calibration, allow_mock=args.allow_mock)
    out_root = args.out_root or (MOCK_OUT if cal.is_mock else DEFAULT_OUT)
    if cal.is_mock and out_root.resolve() == DEFAULT_OUT.resolve():
        print("error: refusing to write MOCK-calibrated clips into data/motions", file=sys.stderr)
        return 2
    names = list(SYNTHETIC_CLIPS) if args.clips == "all" else [c.strip() for c in args.clips.split(",")]
    status = 0
    for name in names:
        clip = make_clip(name, cal)
        res = semantic_to_dropbear(clip.semantic, cal)
        notes = [clip.description]
        if cal.is_mock:
            notes.insert(0, "MOCK calibration: motor values are placeholders; do not train on this clip.")
        sidecar = {
            "source": "synthetic",
            "source_file": f"tools/make_synthetic_motion.py::{name}",
            "source_license": LICENSE,
            "retarget_method": ("MOCK-CALIBRATION (NOT FOR TRAINING): " if cal.is_mock else "")
            + "synthetic: min-jerk keyframes in dropbear-semantic-v1 + semantic-skeleton leg IK (feet planted)",
            "contact_hint": {
                "left": [True] * clip.semantic.num_frames,
                "right": [True] * clip.semantic.num_frames,
                "method": "by construction (both feet planted)",
            },
            "notes": notes,
            "suitability": clip.suitability,
            "saturation": res.saturation,
            "metrics": res.metrics | {"ik_max_residual": clip.ik_residual},
            "synthetic": {k: v for k, v in clip.semantic.meta.items() if k != "semantic_ranges_probe"},
            "semantic_ranges_probe_rad": clip.semantic.meta["semantic_ranges_probe"],
            "calibration": cal.provenance(),
            "pipeline_version": PIPELINE_VERSION,
        }
        sem = clip.semantic
        csv_path, _ = write_motion(
            out_root / "synthetic",
            name,
            fps=FPS,
            root_pos=res.root_pos,
            root_quat_wxyz=res.root_quat_wxyz,
            motor_q=res.motor_q,
            sidecar=sidecar,
            semantic=(sem.pelvis_pos, sem.pelvis_quat_wxyz, sem.q, sem.contacts),
        )
        problems = validate_motion_files(csv_path)
        sat = res.saturation["frames_with_any_saturation_frac"]
        print(json.dumps({"clip": name, "csv": str(csv_path), "frames": sem.num_frames, "saturated_frac": sat,
                          "ik_residual": clip.ik_residual, "metrics": res.metrics, "problems": problems}))
        if problems or sat > 0:
            status = 1
    return status


if __name__ == "__main__":
    raise SystemExit(main())
